config/routes.rb
TEST::Application.routes.draw do
  devise_for :users
  get "welcome/index"

  root to: 'welcome#index'

  resources :users
  resources :product_types do
    resources :products
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :product_type, :order => "created_at DESC"
	attr_accessible :product_type_id, :product_name, :product_description, :product_cost
	validates :product_name, uniqueness: {message: "Name of product is exists" }, presence: true
	validates :product_cost, presence: true, format: { with: /\d+\.+[0-9]/,
    message: "only allows number" }
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
	has_many :products, :dependent => :destroy, :order => "created_at DESC"
	attr_accessible :product_type_name
	validates :product_type_name, uniqueness: {message: "Name of product's type is exists" }, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email, format: { with: /\A([^@\s]+)(@+[a-z]+)(\.+[a-z]+\z)/}
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  respond_to :html, :xml
  protect_from_forgery with: :exception
	before_filter :authenticate_user!
	before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u|
      u.permit(:password, :password_confirmation, :current_password)
    }
  end

end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
	def new
	 	@product_type = ProductType.new
	 end
	 def create
	 	@product_type = ProductType.new(params[:product_type])
	 	if @product_type.save
	 		redirect_to @product_type
	 	else
	 		render 'new'
	 	end
	 end
	 def destroy
		@product_type = ProductType.find(params[:id])
		@product_type.destroy
		render text: "ok"
	end
	def edit
		@product_type = ProductType.find(params[:id])
	end
	def show
		@product_type = ProductType.find(params[:id])
	end

	def index
		@product_types = ProductType.paginate(page: params[:page],:per_page => 10)
		respond_to do |format|
			format.html
			format.xml { render xml: @product_types }
		end
	end
	def update
		@product_types = ProductType.find(params[:id])

		if @product_types.update(params[:product_type])
			redirect_to @product_types
		else
			render 'edit'
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def new
		@product_type = ProductType.find(params[:product_type_id])
		@product = Product.new
	end
	def create
		@product_type = ProductType.find(params[:product_type_id])
		@product = @product_type.products.create(params[:product])
		redirect_to product_type_products_path(@product_type)
	end
	def show
		@product = Product.find(params[:id])
	end
	def destroy
    @product = Product.find(params[:id])
    @product.destroy
    render text: 'ok'
  end
  def edit
    @product_type = ProductType.find(params[:product_type_id])
    @product = Product.find(params[:id])
  end
  def index
		@product_type = ProductType.find(params[:product_type_id])
		@products = @product_type.products.paginate(page: params[:page],:per_page => 10)
		respond_to do |format|
			format.html
			format.xml { render xml: @products }
		end
	end
	def update
		@product = Product.find(params[:id])
		if @product.update(params[:product])
			redirect_to product_type_product_path(@product.product_type, @product)
		else
			render 'edit'
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end
	def create
		@user = User.new(params[:user])
	 	if @user.save
	 		redirect_to product_types_path
	 	else
	 		render 'new'
	 	end
  end
  def index
  	@users = User.paginate(page: params[:page],:per_page => 10)
		respond_to do |format|
	    format.html
	    format.xml { render xml: @users }
	  end
  end
	def update
		@user = User.find(params[:id])

		if @user.update(params[:user])
			redirect_to @user
		else
			render 'edit'
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<html>
<head>
  <title>TEST</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" />
  <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
  <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
  <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/additional-methods.min.js"></script>
</head>
<body>

<nav class="navbar navbar-default col-lg-* col-md-* col-xs-*" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header col-lg-offset-1 col-md-offset-1">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"></a>
    </div><!--navbar-header-->

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li><%= link_to image_tag("/assets/home1.png"), welcome_index_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Manage type of product", product_types_path %></li>
        <%end%>
      </ul>

      <div class="nav navbar-nav navbar-right" style="margin-right: 2%; margin-top: 1%; ">
        <% if user_signed_in? %>
          <!-- Signed in as <%= current_user.email %>. Not you? -->
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

        <% else %>
          <%= link_to "Sign up", new_user_registration_path %>
        <% end %>

      </div>
    </div><!-- /.navbar-collapse -->
  </nav>
  <div class = "body_content col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-xs-*" style = 'margin-left: 11%'>
    <%= yield %>
  </div>

</body>
</html>

app/views/product_types/_form_new_edit.html.erb
<div class='row'>
  <%= form_for @product_type, :html=>{:id=>'form_product_type'} do |f| %>
  <fieldset>
    <div>
      <%= f.label "Type product name", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :product_type_name, :autofocus => true, :class => ' form-control' %>
      </div>
    </div>
    <div class ="form-actions" style="margin-top: 3%" >
      <%= f.submit "Create", :class => 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>
<%= link_to 'Back', product_types_path, :class => 'btn_back btn btn-mini'%>
</div>

app/views/product_types/edit.html.erb
<div class = "page-header">
	<h1>Edit information type of product</h1>
</div>
<%= render "form_new_edit"%>

app/views/product_types/index.html.erb
<div class ="page-header">
<h1>Listing type of product</h1>
</div>


<div>
  <%= link_to 'New type product', new_product_type_path, :class => "btn btn-mini" %>
  <%= link_to 'Back', welcome_index_path, :class => 'btn btn-mini'%>
</div>


<table class="table table-striped">
  <thead>
    <tr>
      <th id='product_type_name'>Name type of product</th>
    </tr>
  </thead>

  <tbody>
  <% @product_types.each do |product_type| %>
    <tr>
      <td class="col-lg-6 col-md-6 col-xs-6"><%= product_type.product_type_name %></td>
      <td>
        <%= link_to 'Show', product_type_path(product_type),:class => 'btn btn-mini' %>
      </td>
      <td>
        <%= link_to "Edit", edit_product_type_path(product_type), :class => 'btn btn-mini' %>
      </td>
      <td >
        <input id= "<%= product_type.id %>" class="delete btn btn-mini btn-danger" type = "button"  value="Delete">
      </td>
    </tr>
  <% end %>
  </tbody>
</table>


<div class =" col-lg-4 col-lg-offset-5 col-md-4 col-md-offset-5 col-xs-*">
  <%=will_paginate @product_types%>
</div>

<div class="dialog" title ="Confirm Delete">
  <p>Are U sure?</p>
</div>
<script type="text/javascript">
$(document).ready(function(){
  $(".dialog").hide();
});
</script>

app/views/product_types/new.html.erb
<div class = "page-header">
	<h1>Create information type of product</h1>
</div>
<%= render "form_new_edit"%>

app/views/product_types/show.html.erb
<div class = "page-header">
	<h3>Type product information</h3>
</div>

	<dl class="dl-horizontal" style='font-size: 120%;'>
		<dt><strong>Name type</strong></dt>
		<dd><%= @product_type.product_type_name %></dd>
	</dl>

<div>
	<%= link_to 'Back', product_types_path, :class=> "btn btn-mini"%>
</div>
<div class='row'>
	<%= link_to "Product of type",  product_type_products_path(@product_type), :style=>'padding-left: 2%;' %>
</div>

app/views/products/_form_new_edit.html.erb
<%= form_for  ([@product_type, @product]), :html=>{:id=>'form_new_edit_product'} do |f| %>

<fieldset>
  <div>
    <%= f.label :product_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :product_name, :autofocus => true, :class => ' form-control'%>
    </div>
  </div>
  <div>
    <%= f.label :product_description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :product_description, :class => ' form-control', :size=>"100x10"%>
    </div>
  </div>
  <div>
    <%= f.label :product_cost, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :product_cost, :class => ' form-control'%>
    </div>
  </div>
  <div class ="form-actions" style="margin-top: 3%" >
    <%= f.submit "Create", :class => 'btn btn-primary' %>
  </div>
</fieldset>
<% end %>
<%= link_to 'Back', product_type_products_path(@product_type), :class => 'btn_back btn btn-mini'%>

app/views/products/_products.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name product</th>
      <th>Product's description</th>
      <th>Cost</th>
    </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.product_name %></td>
      <td><%= product.product_description %></td>
      <td><%= product.product_cost %></td>
      <td>
        <%= link_to 'Show', product_type_product_path(@product_type,product),:class => 'btn btn-mini' %>
      </td>
      <td>
        <%= link_to "Edit", edit_product_type_product_path(@product_type,product), :class => 'btn btn-mini' %>
      </td>
      <td >
        <input id= "<%= product.id %>" class="delete_product btn btn-mini btn-danger" type = "button"  value="Delete">
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/products/edit.html.erb
<div class="page-header">
	<h1>Edit product's information</h1>
</div>
<%= render "form_new_edit"%>

app/views/products/index.html.erb
<div class="page-header">
	<h1>List products of <%= @product_type.product_type_name%></h1>
</div>
<div>
  <%= link_to 'New product', new_product_type_product_path(@product_type), :class => "btn btn-mini" %>
  <%= link_to 'Back', product_types_path, :class => 'btn btn-mini'%>
</div>

<div class="table-content">
  <%= render "products" %>
</div>
<div class =" col-lg-4 col-lg-offset-5 col-md-4 col-md-offset-5 col-xs-* my_pagination">
  <%=will_paginate @products%>
</div>


<div class="dialog" title ="Confirm Delete">
  <p>Are U sure?</p>
</div>
<script type="text/javascript">
$(document).ready(function(){
  $(".dialog").hide();
});
</script>

app/views/products/new.html.erb
<div class="page-header">
	<h1>Create product's information</h1>
</div>
<%= render "form_new_edit"%>

app/views/products/show.html.erb
<div class = "page-header">
	<h3>Product information</h3>
</div>

	<dl class=" row dl-horizontal" style='font-size: 110%;'>
		<dt><strong>Type of product id </strong></dt>
		<dd><%= @product.product_type_id %></dd>

		<dt><strong>Name product  </strong></dt>
		<dd><%= @product.product_name %></dd>

		<dt><strong>Product's description </strong></dt>
		<dd><%= @product.product_description %></dd>

		<dt><strong>Cost </strong></dt>
		<dd><%= @product.product_cost %></dd>
	</dl>

<div>
	<%= link_to 'Back', product_type_products_path, :class=> "btn btn-mini"%>
</div>